# Technical Debt Management Configuration
debt-categories:
  critical:
    labels: ['security', 'crash', 'data-loss', 'vulnerability']
    priority: 1
    sla-days: 3
    color: '#d73a49'
  high:
    labels: ['performance', 'memory-leak', 'accessibility', 'scalability']
    priority: 2
    sla-days: 7
    color: '#fb8500'
  medium:
    labels: ['maintainability', 'complexity', 'duplication', 'code-smell']
    priority: 3
    sla-days: 14
    color: '#ffd60a'
  low:
    labels: ['style', 'documentation', 'naming', 'formatting']
    priority: 4
    sla-days: 30
    color: '#28a745'

sprint-config:
  default-capacity: 40
  debt-allocation-percentage: 20
  min-debt-points: 1
  max-debt-points: 8
  sprint-duration-weeks: 2
  burndown-target-percentage: 15

analysis:
  sonarqube:
    enabled: true
    timeout-minutes: 30
    project-key: 'strategic-planning-platform'
    quality-gate: true
  eslint:
    enabled: true
    config-path: '.eslintrc.js'
    max-warnings: 10
  typescript:
    enabled: true
    config-path: 'tsconfig.json'
    strict-mode: true
  python:
    enabled: true
    tools:
      - bandit # Security
      - pylint # Code quality
      - mypy # Type checking
      - black # Code formatting
  docker:
    enabled: true
    security-scan: true
    best-practices: true

metrics:
  complexity-threshold: 10
  duplication-threshold: 3
  coverage-minimum: 80
  maintainability-index-minimum: 60

rate-limiting:
  api-calls-per-hour: 1000
  batch-size: 30
  delay-between-batches-ms: 1000
  max-retries: 3

notifications:
  slack-enabled: false
  slack-webhook: ''
  teams-enabled: false
  teams-webhook: ''
  email-enabled: false
  email-recipients: []

dashboard:
  update-frequency: 'weekly'
  historical-data-retention-months: 12
  charts-enabled: true
  export-formats: ['md', 'json', 'csv']

automation:
  auto-create-issues: true
  auto-assign: true
  auto-milestone: true
  auto-label: true
  create-epic-issues: true
