global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@aiplatform.example.com'
  smtp_auth_username: 'alerts@aiplatform.example.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@aiplatform.example.com'
        subject: 'AI Platform Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@aiplatform.example.com,oncall@aiplatform.example.com'
        subject: '🚨 CRITICAL Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT - Immediate attention required!

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Timestamp: {{ .StartsAt.Format "2006-01-02 15:04:05" }}

          Runbook: https://docs.aiplatform.example.com/runbooks/{{ .Labels.alertname }}
          Dashboard: https://monitoring.aiplatform.example.com/d/overview
          {{ end }}
    # Uncomment and configure webhook for Slack/Teams/Discord integration
    # webhook_configs:
    #   - url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    #     channel: '#alerts'
    #     title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'admin@aiplatform.example.com'
        subject: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ Warning Alert

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Timestamp: {{ .StartsAt.Format "2006-01-02 15:04:05" }}

          Dashboard: https://monitoring.aiplatform.example.com/d/overview
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

templates:
  - '/etc/alertmanager/templates/*.tmpl'
